language: android
jdk: oraclejdk8
sudo: false
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - ADB_INSTALL_TIMEOUT=10
branches:
  only:
  - master
  - develop
  - /^(feature).*$/
before_script:
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ] && MTB_PR=1 || echo "This is master or not PR"'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && MTB_MERGE_MASTER=1 || echo "This is not master or PR"'
  - echo TRAVIS_BRANCH=${TRAVIS_BRANCH}
  - echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - echo MTB_PR=${MTB_PR}
  - echo MTB_MERGE_MASTER=${MTB_MERGE_MASTER}
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-27.0.2
  - echo y | android update sdk -u -a -t android-27
  - echo y | android update sdk -u -a -t extra-android-support
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
script:
  - ${ANDROID_SDK_HOME}/bin/sdkmanager --list 
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.2
  - android-27
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - '.+'
notifications:
  slack:
    secure: "JgzMYO6RTxsqKDBIlMIAghtyZoWy2pGaQ8bt9tBkVt7x6jVX4uHPy4LQlAOmJbU4AiB5S209QGFJX0NEyOWA2Nje8t67We9dQYjLigyu99brrbJj45EQbeddHNN17V6wELk8INwhwWXnHwamOMCC9jwUy9w2a7pOma6RrBfkBdDGCNhyX8J7uUZ2tbuPCfXbxiv5paX4Y905rxvzDlJekgZfY0cokDC7P/GZ3Y5gt/1BVVLgAmTNHPWtK0Qi0cs34M+N0odXSlJBa9QbKcU0uUVRvVfav51Xe3K+U47aEhRsQ+ZuqWyYuX0DP503ypzV1t2UbXkc7L6IoeB39W7lMIfe/u7zVnoSs9wB0utQ20cLPZT+pAkwMOyiZJqrYaJ/ZorVRcBVqsEgQsDFILyAdUFhN6Eh8kpIYzODvbETSjCgTS5rxgjiJPHegTDf/6mWUwDzxy/uaqlR9uqajcRNHJBHF6XaLjkdjiC8W+x3/fClJfzfLHhRYyKmEC/IFI0TY/rW5UIFquC3KYPoCOav2DtrEyqgP/5VB6KEhtjC0uE/goABcub5ZejMWSUWEKcBrp9V5JbjDCg5+8KO19EURgalNADSVcSsMdtW4KHb3pZuJxmQAHOlNPvaXHcS4vbO/JeIZBez9VdgXy6+LMebSbMbHPQMf7x0KES6dr/VdqY="
